/*
Visitor Identification

The Visitor Identification API allows you to pass identification information to the HubSpot chat widget for otherwise unknown visitors that were verified by your own authentication system.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package visitor_identification

import (
	"encoding/json"
)

// checks if the IdentificationTokenGenerationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdentificationTokenGenerationRequest{}

// IdentificationTokenGenerationRequest Information used to generate a token
type IdentificationTokenGenerationRequest struct {
	// The email of the visitor that you wish to identify
	Email string `json:"email"`
	// The first name of the visitor that you wish to identify. This value will only be set in HubSpot for new contacts and existing contacts where first name is unknown. Optional.
	FirstName *string `json:"firstName,omitempty"`
	// The last name of the visitor that you wish to identify. This value will only be set in HubSpot for new contacts and existing contacts where last name is unknown. Optional.
	LastName *string `json:"lastName,omitempty"`
}

// NewIdentificationTokenGenerationRequest instantiates a new IdentificationTokenGenerationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentificationTokenGenerationRequest(email string) *IdentificationTokenGenerationRequest {
	this := IdentificationTokenGenerationRequest{}
	this.Email = email
	return &this
}

// NewIdentificationTokenGenerationRequestWithDefaults instantiates a new IdentificationTokenGenerationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentificationTokenGenerationRequestWithDefaults() *IdentificationTokenGenerationRequest {
	this := IdentificationTokenGenerationRequest{}
	return &this
}

// GetEmail returns the Email field value
func (o *IdentificationTokenGenerationRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *IdentificationTokenGenerationRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *IdentificationTokenGenerationRequest) SetEmail(v string) {
	o.Email = v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *IdentificationTokenGenerationRequest) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentificationTokenGenerationRequest) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *IdentificationTokenGenerationRequest) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *IdentificationTokenGenerationRequest) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *IdentificationTokenGenerationRequest) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentificationTokenGenerationRequest) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *IdentificationTokenGenerationRequest) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *IdentificationTokenGenerationRequest) SetLastName(v string) {
	o.LastName = &v
}

func (o IdentificationTokenGenerationRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdentificationTokenGenerationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	return toSerialize, nil
}

type NullableIdentificationTokenGenerationRequest struct {
	value *IdentificationTokenGenerationRequest
	isSet bool
}

func (v NullableIdentificationTokenGenerationRequest) Get() *IdentificationTokenGenerationRequest {
	return v.value
}

func (v *NullableIdentificationTokenGenerationRequest) Set(val *IdentificationTokenGenerationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentificationTokenGenerationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentificationTokenGenerationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentificationTokenGenerationRequest(val *IdentificationTokenGenerationRequest) *NullableIdentificationTokenGenerationRequest {
	return &NullableIdentificationTokenGenerationRequest{value: val, isSet: true}
}

func (v NullableIdentificationTokenGenerationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentificationTokenGenerationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
