/*
CRM Objects

Testing BasicApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package objects

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/objects"
)

func Test_objects_BasicApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BasicApiService DeleteCrmV3ObjectsObjectTypeObjectIdArchive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var objectType string
		var objectId string

		httpRes, err := apiClient.BasicApi.DeleteCrmV3ObjectsObjectTypeObjectIdArchive(context.Background(), objectType, objectId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService GetCrmV3ObjectsObjectTypeGetPage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var objectType string

		resp, httpRes, err := apiClient.BasicApi.GetCrmV3ObjectsObjectTypeGetPage(context.Background(), objectType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService GetCrmV3ObjectsObjectTypeObjectIdGetById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var objectType string
		var objectId string

		resp, httpRes, err := apiClient.BasicApi.GetCrmV3ObjectsObjectTypeObjectIdGetById(context.Background(), objectType, objectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService PatchCrmV3ObjectsObjectTypeObjectIdUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var objectType string
		var objectId string

		resp, httpRes, err := apiClient.BasicApi.PatchCrmV3ObjectsObjectTypeObjectIdUpdate(context.Background(), objectType, objectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService PostCrmV3ObjectsObjectTypeCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var objectType string

		resp, httpRes, err := apiClient.BasicApi.PostCrmV3ObjectsObjectTypeCreate(context.Background(), objectType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
