/*
CRM Objects

Testing GDPRApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package objects

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/objects"
)

func Test_objects_GDPRApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GDPRApiService PostCrmV3ObjectsObjectTypeGdprDeletePurge", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var objectType string

		httpRes, err := apiClient.GDPRApi.PostCrmV3ObjectsObjectTypeGdprDeletePurge(context.Background(), objectType).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
