/*
Properties

Testing GroupsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package properties

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/properties"
)

func Test_properties_GroupsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GroupsApiService DeleteCrmV3PropertiesObjectTypeGroupsGroupNameArchive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var objectType string
		var groupName string

		httpRes, err := apiClient.GroupsApi.DeleteCrmV3PropertiesObjectTypeGroupsGroupNameArchive(context.Background(), objectType, groupName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GroupsApiService GetCrmV3PropertiesObjectTypeGroupsGetAll", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var objectType string

		resp, httpRes, err := apiClient.GroupsApi.GetCrmV3PropertiesObjectTypeGroupsGetAll(context.Background(), objectType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GroupsApiService GetCrmV3PropertiesObjectTypeGroupsGroupNameGetByName", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var objectType string
		var groupName string

		resp, httpRes, err := apiClient.GroupsApi.GetCrmV3PropertiesObjectTypeGroupsGroupNameGetByName(context.Background(), objectType, groupName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GroupsApiService PatchCrmV3PropertiesObjectTypeGroupsGroupNameUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var objectType string
		var groupName string

		resp, httpRes, err := apiClient.GroupsApi.PatchCrmV3PropertiesObjectTypeGroupsGroupNameUpdate(context.Background(), objectType, groupName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GroupsApiService PostCrmV3PropertiesObjectTypeGroupsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var objectType string

		resp, httpRes, err := apiClient.GroupsApi.PostCrmV3PropertiesObjectTypeGroupsCreate(context.Background(), objectType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
