/*
Properties

Testing BatchApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package properties

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/properties"
)

func Test_properties_BatchApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BatchApiService PostCrmV3PropertiesObjectTypeBatchArchiveArchive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var objectType string

		httpRes, err := apiClient.BatchApi.PostCrmV3PropertiesObjectTypeBatchArchiveArchive(context.Background(), objectType).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BatchApiService PostCrmV3PropertiesObjectTypeBatchCreateCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var objectType string

		resp, httpRes, err := apiClient.BatchApi.PostCrmV3PropertiesObjectTypeBatchCreateCreate(context.Background(), objectType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BatchApiService PostCrmV3PropertiesObjectTypeBatchReadRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var objectType string

		resp, httpRes, err := apiClient.BatchApi.PostCrmV3PropertiesObjectTypeBatchReadRead(context.Background(), objectType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
