/*
CMS Source Code

Testing ContentApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package source_code

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/cms/source_code"
)

func Test_source_code_ContentApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ContentApiService DeleteCmsV3SourceCodeEnvironmentContentPathArchive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var environment string
		var path string

		httpRes, err := apiClient.ContentApi.DeleteCmsV3SourceCodeEnvironmentContentPathArchive(context.Background(), environment, path).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentApiService GetCmsV3SourceCodeEnvironmentContentPathGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var environment string
		var path string

		resp, httpRes, err := apiClient.ContentApi.GetCmsV3SourceCodeEnvironmentContentPathGet(context.Background(), environment, path).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentApiService PostCmsV3SourceCodeEnvironmentContentPathCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var environment string
		var path string

		resp, httpRes, err := apiClient.ContentApi.PostCmsV3SourceCodeEnvironmentContentPathCreate(context.Background(), environment, path).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentApiService PutCmsV3SourceCodeEnvironmentContentPathReplace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var environment string
		var path string

		resp, httpRes, err := apiClient.ContentApi.PutCmsV3SourceCodeEnvironmentContentPathReplace(context.Background(), environment, path).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
