/*
CMS Source Code

Testing ExtractApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package source_code

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/cms/source_code"
)

func Test_source_code_ExtractApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ExtractApiService PostCmsV3SourceCodeExtractPathExtractByPath", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var path string

		httpRes, err := apiClient.ExtractApi.PostCmsV3SourceCodeExtractPathExtractByPath(context.Background(), path).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
