/*
CMS Source Code

Testing MetadataApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package source_code

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/cms/source_code"
)

func Test_source_code_MetadataApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MetadataApiService GetCmsV3SourceCodeEnvironmentMetadataPathGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var environment string
		var path string

		resp, httpRes, err := apiClient.MetadataApi.GetCmsV3SourceCodeEnvironmentMetadataPathGet(context.Background(), environment, path).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
