/*
Contacts

Testing BasicApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package contacts

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/contacts"
)

func Test_contacts_BasicApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BasicApiService DeleteCrmV3ObjectsContactsContactIdArchive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var contactId string

		httpRes, err := apiClient.BasicApi.DeleteCrmV3ObjectsContactsContactIdArchive(context.Background(), contactId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService GetCrmV3ObjectsContactsContactIdGetById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var contactId string

		resp, httpRes, err := apiClient.BasicApi.GetCrmV3ObjectsContactsContactIdGetById(context.Background(), contactId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService GetCrmV3ObjectsContactsGetPage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BasicApi.GetCrmV3ObjectsContactsGetPage(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService PatchCrmV3ObjectsContactsContactIdUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var contactId string

		resp, httpRes, err := apiClient.BasicApi.PatchCrmV3ObjectsContactsContactIdUpdate(context.Background(), contactId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService PostCrmV3ObjectsContactsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BasicApi.PostCrmV3ObjectsContactsCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
