/*
Contacts

Testing GDPRApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package contacts

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/contacts"
)

func Test_contacts_GDPRApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GDPRApiService PostCrmV3ObjectsContactsGdprDeletePurge", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.GDPRApi.PostCrmV3ObjectsContactsGdprDeletePurge(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
