/*
Accounting Extension

These APIs allow you to interact with HubSpot's Accounting Extension. It allows you to: * Specify the URLs that HubSpot will use when making webhook requests to your external accounting system. * Respond to webhook calls made to your external accounting system by HubSpot

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package accounting

import (
	"encoding/json"
)

// checks if the AccountingAppUrls type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountingAppUrls{}

// AccountingAppUrls The URL endpoints that HubSpot will send requests to an external accounting system for certain actions.
type AccountingAppUrls struct {
	// A URL that specifies the endpoint where invoices can be retrieved.
	GetInvoiceUrl string `json:"getInvoiceUrl"`
	// A URL that specifies the endpoint where a customer search can be performed.
	SearchCustomerUrl string `json:"searchCustomerUrl"`
	// A URL that specifies the endpoint where an invoice PDF can be retrieved.
	GetInvoicePdfUrl string `json:"getInvoicePdfUrl"`
	// A template URL that indicates the endpoint where a customer can be fetched by ID. Note that ${CUSTOMER_ID} in this URL will be replaced by the actual customer ID. For example: https://myapp.com/api/customers/${CUSTOMER_ID}
	CustomerUrlTemplate string `json:"customerUrlTemplate"`
	// A template URL that indicates the endpoint where a product can be fetched by ID. Note that ${PRODUCT_ID} in this URL will be replaced by the actual product ID. For example: https://myapp.com/api/products/${PRODUCT_ID}
	ProductUrlTemplate string `json:"productUrlTemplate"`
	// A template URL that indicates the endpoint where an invoice can be fetched by ID. Note that ${INVOICE_ID} in this URL will be replaced by the actual invoice ID. For example: https://myapp.com/api/invoices/${INVOICE_ID}
	InvoiceUrlTemplate string `json:"invoiceUrlTemplate"`
	// A URL that specifies the endpoint where an invoices can be created.
	CreateInvoiceUrl *string `json:"createInvoiceUrl,omitempty"`
	// A URL that specifies the endpoint where an invoice search can be performed.
	SearchInvoiceUrl *string `json:"searchInvoiceUrl,omitempty"`
	// A URL that specifies the endpoint where a product search can be performed.
	SearchProductUrl *string `json:"searchProductUrl,omitempty"`
	// A URL that specifies the endpoint where payment terms can be retrieved.
	GetTermsUrl *string `json:"getTermsUrl,omitempty"`
	// A URL that specifies the endpoint where a new customer can be created.
	CreateCustomerUrl *string `json:"createCustomerUrl,omitempty"`
	// A URL that specifies the endpoint where a tax search can be performed.
	SearchTaxUrl *string `json:"searchTaxUrl,omitempty"`
	// A URL that specifies the endpoint where exchange rates can be queried.
	ExchangeRateUrl *string `json:"exchangeRateUrl,omitempty"`
	SearchUrl       *string `json:"searchUrl,omitempty"`
	SearchCountUrl  *string `json:"searchCountUrl,omitempty"`
}

// NewAccountingAppUrls instantiates a new AccountingAppUrls object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountingAppUrls(getInvoiceUrl string, searchCustomerUrl string, getInvoicePdfUrl string, customerUrlTemplate string, productUrlTemplate string, invoiceUrlTemplate string) *AccountingAppUrls {
	this := AccountingAppUrls{}
	this.GetInvoiceUrl = getInvoiceUrl
	this.SearchCustomerUrl = searchCustomerUrl
	this.GetInvoicePdfUrl = getInvoicePdfUrl
	this.CustomerUrlTemplate = customerUrlTemplate
	this.ProductUrlTemplate = productUrlTemplate
	this.InvoiceUrlTemplate = invoiceUrlTemplate
	return &this
}

// NewAccountingAppUrlsWithDefaults instantiates a new AccountingAppUrls object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountingAppUrlsWithDefaults() *AccountingAppUrls {
	this := AccountingAppUrls{}
	return &this
}

// GetGetInvoiceUrl returns the GetInvoiceUrl field value
func (o *AccountingAppUrls) GetGetInvoiceUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GetInvoiceUrl
}

// GetGetInvoiceUrlOk returns a tuple with the GetInvoiceUrl field value
// and a boolean to check if the value has been set.
func (o *AccountingAppUrls) GetGetInvoiceUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GetInvoiceUrl, true
}

// SetGetInvoiceUrl sets field value
func (o *AccountingAppUrls) SetGetInvoiceUrl(v string) {
	o.GetInvoiceUrl = v
}

// GetSearchCustomerUrl returns the SearchCustomerUrl field value
func (o *AccountingAppUrls) GetSearchCustomerUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SearchCustomerUrl
}

// GetSearchCustomerUrlOk returns a tuple with the SearchCustomerUrl field value
// and a boolean to check if the value has been set.
func (o *AccountingAppUrls) GetSearchCustomerUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SearchCustomerUrl, true
}

// SetSearchCustomerUrl sets field value
func (o *AccountingAppUrls) SetSearchCustomerUrl(v string) {
	o.SearchCustomerUrl = v
}

// GetGetInvoicePdfUrl returns the GetInvoicePdfUrl field value
func (o *AccountingAppUrls) GetGetInvoicePdfUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GetInvoicePdfUrl
}

// GetGetInvoicePdfUrlOk returns a tuple with the GetInvoicePdfUrl field value
// and a boolean to check if the value has been set.
func (o *AccountingAppUrls) GetGetInvoicePdfUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GetInvoicePdfUrl, true
}

// SetGetInvoicePdfUrl sets field value
func (o *AccountingAppUrls) SetGetInvoicePdfUrl(v string) {
	o.GetInvoicePdfUrl = v
}

// GetCustomerUrlTemplate returns the CustomerUrlTemplate field value
func (o *AccountingAppUrls) GetCustomerUrlTemplate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerUrlTemplate
}

// GetCustomerUrlTemplateOk returns a tuple with the CustomerUrlTemplate field value
// and a boolean to check if the value has been set.
func (o *AccountingAppUrls) GetCustomerUrlTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerUrlTemplate, true
}

// SetCustomerUrlTemplate sets field value
func (o *AccountingAppUrls) SetCustomerUrlTemplate(v string) {
	o.CustomerUrlTemplate = v
}

// GetProductUrlTemplate returns the ProductUrlTemplate field value
func (o *AccountingAppUrls) GetProductUrlTemplate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductUrlTemplate
}

// GetProductUrlTemplateOk returns a tuple with the ProductUrlTemplate field value
// and a boolean to check if the value has been set.
func (o *AccountingAppUrls) GetProductUrlTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductUrlTemplate, true
}

// SetProductUrlTemplate sets field value
func (o *AccountingAppUrls) SetProductUrlTemplate(v string) {
	o.ProductUrlTemplate = v
}

// GetInvoiceUrlTemplate returns the InvoiceUrlTemplate field value
func (o *AccountingAppUrls) GetInvoiceUrlTemplate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InvoiceUrlTemplate
}

// GetInvoiceUrlTemplateOk returns a tuple with the InvoiceUrlTemplate field value
// and a boolean to check if the value has been set.
func (o *AccountingAppUrls) GetInvoiceUrlTemplateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvoiceUrlTemplate, true
}

// SetInvoiceUrlTemplate sets field value
func (o *AccountingAppUrls) SetInvoiceUrlTemplate(v string) {
	o.InvoiceUrlTemplate = v
}

// GetCreateInvoiceUrl returns the CreateInvoiceUrl field value if set, zero value otherwise.
func (o *AccountingAppUrls) GetCreateInvoiceUrl() string {
	if o == nil || IsNil(o.CreateInvoiceUrl) {
		var ret string
		return ret
	}
	return *o.CreateInvoiceUrl
}

// GetCreateInvoiceUrlOk returns a tuple with the CreateInvoiceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountingAppUrls) GetCreateInvoiceUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CreateInvoiceUrl) {
		return nil, false
	}
	return o.CreateInvoiceUrl, true
}

// HasCreateInvoiceUrl returns a boolean if a field has been set.
func (o *AccountingAppUrls) HasCreateInvoiceUrl() bool {
	if o != nil && !IsNil(o.CreateInvoiceUrl) {
		return true
	}

	return false
}

// SetCreateInvoiceUrl gets a reference to the given string and assigns it to the CreateInvoiceUrl field.
func (o *AccountingAppUrls) SetCreateInvoiceUrl(v string) {
	o.CreateInvoiceUrl = &v
}

// GetSearchInvoiceUrl returns the SearchInvoiceUrl field value if set, zero value otherwise.
func (o *AccountingAppUrls) GetSearchInvoiceUrl() string {
	if o == nil || IsNil(o.SearchInvoiceUrl) {
		var ret string
		return ret
	}
	return *o.SearchInvoiceUrl
}

// GetSearchInvoiceUrlOk returns a tuple with the SearchInvoiceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountingAppUrls) GetSearchInvoiceUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SearchInvoiceUrl) {
		return nil, false
	}
	return o.SearchInvoiceUrl, true
}

// HasSearchInvoiceUrl returns a boolean if a field has been set.
func (o *AccountingAppUrls) HasSearchInvoiceUrl() bool {
	if o != nil && !IsNil(o.SearchInvoiceUrl) {
		return true
	}

	return false
}

// SetSearchInvoiceUrl gets a reference to the given string and assigns it to the SearchInvoiceUrl field.
func (o *AccountingAppUrls) SetSearchInvoiceUrl(v string) {
	o.SearchInvoiceUrl = &v
}

// GetSearchProductUrl returns the SearchProductUrl field value if set, zero value otherwise.
func (o *AccountingAppUrls) GetSearchProductUrl() string {
	if o == nil || IsNil(o.SearchProductUrl) {
		var ret string
		return ret
	}
	return *o.SearchProductUrl
}

// GetSearchProductUrlOk returns a tuple with the SearchProductUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountingAppUrls) GetSearchProductUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SearchProductUrl) {
		return nil, false
	}
	return o.SearchProductUrl, true
}

// HasSearchProductUrl returns a boolean if a field has been set.
func (o *AccountingAppUrls) HasSearchProductUrl() bool {
	if o != nil && !IsNil(o.SearchProductUrl) {
		return true
	}

	return false
}

// SetSearchProductUrl gets a reference to the given string and assigns it to the SearchProductUrl field.
func (o *AccountingAppUrls) SetSearchProductUrl(v string) {
	o.SearchProductUrl = &v
}

// GetGetTermsUrl returns the GetTermsUrl field value if set, zero value otherwise.
func (o *AccountingAppUrls) GetGetTermsUrl() string {
	if o == nil || IsNil(o.GetTermsUrl) {
		var ret string
		return ret
	}
	return *o.GetTermsUrl
}

// GetGetTermsUrlOk returns a tuple with the GetTermsUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountingAppUrls) GetGetTermsUrlOk() (*string, bool) {
	if o == nil || IsNil(o.GetTermsUrl) {
		return nil, false
	}
	return o.GetTermsUrl, true
}

// HasGetTermsUrl returns a boolean if a field has been set.
func (o *AccountingAppUrls) HasGetTermsUrl() bool {
	if o != nil && !IsNil(o.GetTermsUrl) {
		return true
	}

	return false
}

// SetGetTermsUrl gets a reference to the given string and assigns it to the GetTermsUrl field.
func (o *AccountingAppUrls) SetGetTermsUrl(v string) {
	o.GetTermsUrl = &v
}

// GetCreateCustomerUrl returns the CreateCustomerUrl field value if set, zero value otherwise.
func (o *AccountingAppUrls) GetCreateCustomerUrl() string {
	if o == nil || IsNil(o.CreateCustomerUrl) {
		var ret string
		return ret
	}
	return *o.CreateCustomerUrl
}

// GetCreateCustomerUrlOk returns a tuple with the CreateCustomerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountingAppUrls) GetCreateCustomerUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CreateCustomerUrl) {
		return nil, false
	}
	return o.CreateCustomerUrl, true
}

// HasCreateCustomerUrl returns a boolean if a field has been set.
func (o *AccountingAppUrls) HasCreateCustomerUrl() bool {
	if o != nil && !IsNil(o.CreateCustomerUrl) {
		return true
	}

	return false
}

// SetCreateCustomerUrl gets a reference to the given string and assigns it to the CreateCustomerUrl field.
func (o *AccountingAppUrls) SetCreateCustomerUrl(v string) {
	o.CreateCustomerUrl = &v
}

// GetSearchTaxUrl returns the SearchTaxUrl field value if set, zero value otherwise.
func (o *AccountingAppUrls) GetSearchTaxUrl() string {
	if o == nil || IsNil(o.SearchTaxUrl) {
		var ret string
		return ret
	}
	return *o.SearchTaxUrl
}

// GetSearchTaxUrlOk returns a tuple with the SearchTaxUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountingAppUrls) GetSearchTaxUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SearchTaxUrl) {
		return nil, false
	}
	return o.SearchTaxUrl, true
}

// HasSearchTaxUrl returns a boolean if a field has been set.
func (o *AccountingAppUrls) HasSearchTaxUrl() bool {
	if o != nil && !IsNil(o.SearchTaxUrl) {
		return true
	}

	return false
}

// SetSearchTaxUrl gets a reference to the given string and assigns it to the SearchTaxUrl field.
func (o *AccountingAppUrls) SetSearchTaxUrl(v string) {
	o.SearchTaxUrl = &v
}

// GetExchangeRateUrl returns the ExchangeRateUrl field value if set, zero value otherwise.
func (o *AccountingAppUrls) GetExchangeRateUrl() string {
	if o == nil || IsNil(o.ExchangeRateUrl) {
		var ret string
		return ret
	}
	return *o.ExchangeRateUrl
}

// GetExchangeRateUrlOk returns a tuple with the ExchangeRateUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountingAppUrls) GetExchangeRateUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ExchangeRateUrl) {
		return nil, false
	}
	return o.ExchangeRateUrl, true
}

// HasExchangeRateUrl returns a boolean if a field has been set.
func (o *AccountingAppUrls) HasExchangeRateUrl() bool {
	if o != nil && !IsNil(o.ExchangeRateUrl) {
		return true
	}

	return false
}

// SetExchangeRateUrl gets a reference to the given string and assigns it to the ExchangeRateUrl field.
func (o *AccountingAppUrls) SetExchangeRateUrl(v string) {
	o.ExchangeRateUrl = &v
}

// GetSearchUrl returns the SearchUrl field value if set, zero value otherwise.
func (o *AccountingAppUrls) GetSearchUrl() string {
	if o == nil || IsNil(o.SearchUrl) {
		var ret string
		return ret
	}
	return *o.SearchUrl
}

// GetSearchUrlOk returns a tuple with the SearchUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountingAppUrls) GetSearchUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SearchUrl) {
		return nil, false
	}
	return o.SearchUrl, true
}

// HasSearchUrl returns a boolean if a field has been set.
func (o *AccountingAppUrls) HasSearchUrl() bool {
	if o != nil && !IsNil(o.SearchUrl) {
		return true
	}

	return false
}

// SetSearchUrl gets a reference to the given string and assigns it to the SearchUrl field.
func (o *AccountingAppUrls) SetSearchUrl(v string) {
	o.SearchUrl = &v
}

// GetSearchCountUrl returns the SearchCountUrl field value if set, zero value otherwise.
func (o *AccountingAppUrls) GetSearchCountUrl() string {
	if o == nil || IsNil(o.SearchCountUrl) {
		var ret string
		return ret
	}
	return *o.SearchCountUrl
}

// GetSearchCountUrlOk returns a tuple with the SearchCountUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountingAppUrls) GetSearchCountUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SearchCountUrl) {
		return nil, false
	}
	return o.SearchCountUrl, true
}

// HasSearchCountUrl returns a boolean if a field has been set.
func (o *AccountingAppUrls) HasSearchCountUrl() bool {
	if o != nil && !IsNil(o.SearchCountUrl) {
		return true
	}

	return false
}

// SetSearchCountUrl gets a reference to the given string and assigns it to the SearchCountUrl field.
func (o *AccountingAppUrls) SetSearchCountUrl(v string) {
	o.SearchCountUrl = &v
}

func (o AccountingAppUrls) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountingAppUrls) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["getInvoiceUrl"] = o.GetInvoiceUrl
	toSerialize["searchCustomerUrl"] = o.SearchCustomerUrl
	toSerialize["getInvoicePdfUrl"] = o.GetInvoicePdfUrl
	toSerialize["customerUrlTemplate"] = o.CustomerUrlTemplate
	toSerialize["productUrlTemplate"] = o.ProductUrlTemplate
	toSerialize["invoiceUrlTemplate"] = o.InvoiceUrlTemplate
	if !IsNil(o.CreateInvoiceUrl) {
		toSerialize["createInvoiceUrl"] = o.CreateInvoiceUrl
	}
	if !IsNil(o.SearchInvoiceUrl) {
		toSerialize["searchInvoiceUrl"] = o.SearchInvoiceUrl
	}
	if !IsNil(o.SearchProductUrl) {
		toSerialize["searchProductUrl"] = o.SearchProductUrl
	}
	if !IsNil(o.GetTermsUrl) {
		toSerialize["getTermsUrl"] = o.GetTermsUrl
	}
	if !IsNil(o.CreateCustomerUrl) {
		toSerialize["createCustomerUrl"] = o.CreateCustomerUrl
	}
	if !IsNil(o.SearchTaxUrl) {
		toSerialize["searchTaxUrl"] = o.SearchTaxUrl
	}
	if !IsNil(o.ExchangeRateUrl) {
		toSerialize["exchangeRateUrl"] = o.ExchangeRateUrl
	}
	if !IsNil(o.SearchUrl) {
		toSerialize["searchUrl"] = o.SearchUrl
	}
	if !IsNil(o.SearchCountUrl) {
		toSerialize["searchCountUrl"] = o.SearchCountUrl
	}
	return toSerialize, nil
}

type NullableAccountingAppUrls struct {
	value *AccountingAppUrls
	isSet bool
}

func (v NullableAccountingAppUrls) Get() *AccountingAppUrls {
	return v.value
}

func (v *NullableAccountingAppUrls) Set(val *AccountingAppUrls) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountingAppUrls) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountingAppUrls) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountingAppUrls(val *AccountingAppUrls) *NullableAccountingAppUrls {
	return &NullableAccountingAppUrls{value: val, isSet: true}
}

func (v NullableAccountingAppUrls) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountingAppUrls) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
