/*
CRM Imports

Testing PublicImportsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package imports

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/imports"
)

func Test_imports_PublicImportsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PublicImportsApiService GetCrmV3ImportsImportIdErrorsGetErrors", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var importId int64

		resp, httpRes, err := apiClient.PublicImportsApi.GetCrmV3ImportsImportIdErrorsGetErrors(context.Background(), importId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
