/*

Testing RefreshTokensApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package oauth

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/auth/oauth"
)

func Test_oauth_RefreshTokensApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RefreshTokensApiService DeleteOauthV1RefreshTokensTokenArchive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var token string

		httpRes, err := apiClient.RefreshTokensApi.DeleteOauthV1RefreshTokensTokenArchive(context.Background(), token).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RefreshTokensApiService GetOauthV1RefreshTokensTokenGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var token string

		resp, httpRes, err := apiClient.RefreshTokensApi.GetOauthV1RefreshTokensTokenGet(context.Background(), token).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
