/*
Schemas

Testing PublicObjectSchemasApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package schemas

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/schemas"
)

func Test_schemas_PublicObjectSchemasApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PublicObjectSchemasApiService DeleteCrmObjectSchemasV3SchemasObjectTypePurgePurge", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var objectType string

		httpRes, err := apiClient.PublicObjectSchemasApi.DeleteCrmObjectSchemasV3SchemasObjectTypePurgePurge(context.Background(), objectType).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
