/*
CMS Performance API

Testing PublicPerformanceApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package performance

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/cms/performance"
)

func Test_performance_PublicPerformanceApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PublicPerformanceApiService GetCmsV3PerformanceGetPage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PublicPerformanceApi.GetCmsV3PerformanceGetPage(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicPerformanceApiService GetCmsV3PerformanceUptimeGetUptime", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PublicPerformanceApi.GetCmsV3PerformanceUptimeGetUptime(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
