/*
Blog Post endpoints

Use these endpoints for interacting with Blog Posts, Blog Authors, and Blog Tags

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blog-posts

import (
	"encoding/json"
)

// checks if the Styles type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Styles{}

// Styles struct for Styles
type Styles struct {
	VerticalAlignment string `json:"verticalAlignment"`
	BackgroundColor RGBAColor `json:"backgroundColor"`
	BackgroundImage BackgroundImage `json:"backgroundImage"`
	BackgroundGradient Gradient `json:"backgroundGradient"`
	MaxWidthSectionCentering int32 `json:"maxWidthSectionCentering"`
	ForceFullWidthSection bool `json:"forceFullWidthSection"`
	FlexboxPositioning string `json:"flexboxPositioning"`
}

// NewStyles instantiates a new Styles object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStyles(verticalAlignment string, backgroundColor RGBAColor, backgroundImage BackgroundImage, backgroundGradient Gradient, maxWidthSectionCentering int32, forceFullWidthSection bool, flexboxPositioning string) *Styles {
	this := Styles{}
	this.VerticalAlignment = verticalAlignment
	this.BackgroundColor = backgroundColor
	this.BackgroundImage = backgroundImage
	this.BackgroundGradient = backgroundGradient
	this.MaxWidthSectionCentering = maxWidthSectionCentering
	this.ForceFullWidthSection = forceFullWidthSection
	this.FlexboxPositioning = flexboxPositioning
	return &this
}

// NewStylesWithDefaults instantiates a new Styles object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStylesWithDefaults() *Styles {
	this := Styles{}
	return &this
}

// GetVerticalAlignment returns the VerticalAlignment field value
func (o *Styles) GetVerticalAlignment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerticalAlignment
}

// GetVerticalAlignmentOk returns a tuple with the VerticalAlignment field value
// and a boolean to check if the value has been set.
func (o *Styles) GetVerticalAlignmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerticalAlignment, true
}

// SetVerticalAlignment sets field value
func (o *Styles) SetVerticalAlignment(v string) {
	o.VerticalAlignment = v
}

// GetBackgroundColor returns the BackgroundColor field value
func (o *Styles) GetBackgroundColor() RGBAColor {
	if o == nil {
		var ret RGBAColor
		return ret
	}

	return o.BackgroundColor
}

// GetBackgroundColorOk returns a tuple with the BackgroundColor field value
// and a boolean to check if the value has been set.
func (o *Styles) GetBackgroundColorOk() (*RGBAColor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BackgroundColor, true
}

// SetBackgroundColor sets field value
func (o *Styles) SetBackgroundColor(v RGBAColor) {
	o.BackgroundColor = v
}

// GetBackgroundImage returns the BackgroundImage field value
func (o *Styles) GetBackgroundImage() BackgroundImage {
	if o == nil {
		var ret BackgroundImage
		return ret
	}

	return o.BackgroundImage
}

// GetBackgroundImageOk returns a tuple with the BackgroundImage field value
// and a boolean to check if the value has been set.
func (o *Styles) GetBackgroundImageOk() (*BackgroundImage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BackgroundImage, true
}

// SetBackgroundImage sets field value
func (o *Styles) SetBackgroundImage(v BackgroundImage) {
	o.BackgroundImage = v
}

// GetBackgroundGradient returns the BackgroundGradient field value
func (o *Styles) GetBackgroundGradient() Gradient {
	if o == nil {
		var ret Gradient
		return ret
	}

	return o.BackgroundGradient
}

// GetBackgroundGradientOk returns a tuple with the BackgroundGradient field value
// and a boolean to check if the value has been set.
func (o *Styles) GetBackgroundGradientOk() (*Gradient, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BackgroundGradient, true
}

// SetBackgroundGradient sets field value
func (o *Styles) SetBackgroundGradient(v Gradient) {
	o.BackgroundGradient = v
}

// GetMaxWidthSectionCentering returns the MaxWidthSectionCentering field value
func (o *Styles) GetMaxWidthSectionCentering() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxWidthSectionCentering
}

// GetMaxWidthSectionCenteringOk returns a tuple with the MaxWidthSectionCentering field value
// and a boolean to check if the value has been set.
func (o *Styles) GetMaxWidthSectionCenteringOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxWidthSectionCentering, true
}

// SetMaxWidthSectionCentering sets field value
func (o *Styles) SetMaxWidthSectionCentering(v int32) {
	o.MaxWidthSectionCentering = v
}

// GetForceFullWidthSection returns the ForceFullWidthSection field value
func (o *Styles) GetForceFullWidthSection() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ForceFullWidthSection
}

// GetForceFullWidthSectionOk returns a tuple with the ForceFullWidthSection field value
// and a boolean to check if the value has been set.
func (o *Styles) GetForceFullWidthSectionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ForceFullWidthSection, true
}

// SetForceFullWidthSection sets field value
func (o *Styles) SetForceFullWidthSection(v bool) {
	o.ForceFullWidthSection = v
}

// GetFlexboxPositioning returns the FlexboxPositioning field value
func (o *Styles) GetFlexboxPositioning() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FlexboxPositioning
}

// GetFlexboxPositioningOk returns a tuple with the FlexboxPositioning field value
// and a boolean to check if the value has been set.
func (o *Styles) GetFlexboxPositioningOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FlexboxPositioning, true
}

// SetFlexboxPositioning sets field value
func (o *Styles) SetFlexboxPositioning(v string) {
	o.FlexboxPositioning = v
}

func (o Styles) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Styles) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["verticalAlignment"] = o.VerticalAlignment
	toSerialize["backgroundColor"] = o.BackgroundColor
	toSerialize["backgroundImage"] = o.BackgroundImage
	toSerialize["backgroundGradient"] = o.BackgroundGradient
	toSerialize["maxWidthSectionCentering"] = o.MaxWidthSectionCentering
	toSerialize["forceFullWidthSection"] = o.ForceFullWidthSection
	toSerialize["flexboxPositioning"] = o.FlexboxPositioning
	return toSerialize, nil
}

type NullableStyles struct {
	value *Styles
	isSet bool
}

func (v NullableStyles) Get() *Styles {
	return v.value
}

func (v *NullableStyles) Set(val *Styles) {
	v.value = val
	v.isSet = true
}

func (v NullableStyles) IsSet() bool {
	return v.isSet
}

func (v *NullableStyles) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStyles(val *Styles) *NullableStyles {
	return &NullableStyles{value: val, isSet: true}
}

func (v NullableStyles) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStyles) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


