/*
Tickets

Testing BasicApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package tickets

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/tickets"
)

func Test_tickets_BasicApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BasicApiService DeleteCrmV3ObjectsTicketsTicketIdArchive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ticketId string

		httpRes, err := apiClient.BasicApi.DeleteCrmV3ObjectsTicketsTicketIdArchive(context.Background(), ticketId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService GetCrmV3ObjectsTicketsGetPage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BasicApi.GetCrmV3ObjectsTicketsGetPage(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService GetCrmV3ObjectsTicketsTicketIdGetById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ticketId string

		resp, httpRes, err := apiClient.BasicApi.GetCrmV3ObjectsTicketsTicketIdGetById(context.Background(), ticketId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService PatchCrmV3ObjectsTicketsTicketIdUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ticketId string

		resp, httpRes, err := apiClient.BasicApi.PatchCrmV3ObjectsTicketsTicketIdUpdate(context.Background(), ticketId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService PostCrmV3ObjectsTicketsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BasicApi.PostCrmV3ObjectsTicketsCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
