/*
Quotes

Testing BasicApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package quotes

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/quotes"
)

func Test_quotes_BasicApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BasicApiService DeleteCrmV3ObjectsQuotesQuoteIdArchive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var quoteId string

		httpRes, err := apiClient.BasicApi.DeleteCrmV3ObjectsQuotesQuoteIdArchive(context.Background(), quoteId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService GetCrmV3ObjectsQuotesGetPage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BasicApi.GetCrmV3ObjectsQuotesGetPage(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService GetCrmV3ObjectsQuotesQuoteIdGetById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var quoteId string

		resp, httpRes, err := apiClient.BasicApi.GetCrmV3ObjectsQuotesQuoteIdGetById(context.Background(), quoteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService PatchCrmV3ObjectsQuotesQuoteIdUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var quoteId string

		resp, httpRes, err := apiClient.BasicApi.PatchCrmV3ObjectsQuotesQuoteIdUpdate(context.Background(), quoteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService PostCrmV3ObjectsQuotesCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BasicApi.PostCrmV3ObjectsQuotesCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
