/*
Custom Workflow Actions

Testing CallbacksApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package actions

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/automation/actions"
)

func Test_actions_CallbacksApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CallbacksApiService PostAutomationV4ActionsCallbacksCallbackIdCompleteComplete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var callbackId string

		httpRes, err := apiClient.CallbacksApi.PostAutomationV4ActionsCallbacksCallbackIdCompleteComplete(context.Background(), callbackId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CallbacksApiService PostAutomationV4ActionsCallbacksCompleteCompleteBatch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.CallbacksApi.PostAutomationV4ActionsCallbacksCompleteCompleteBatch(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
