/*
Custom Workflow Actions

Testing RevisionsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package actions

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/automation/actions"
)

func Test_actions_RevisionsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RevisionsApiService GetAutomationV4ActionsAppIdDefinitionIdRevisionsGetPage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var definitionId string
		var appId int32

		resp, httpRes, err := apiClient.RevisionsApi.GetAutomationV4ActionsAppIdDefinitionIdRevisionsGetPage(context.Background(), definitionId, appId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RevisionsApiService GetAutomationV4ActionsAppIdDefinitionIdRevisionsRevisionIdGetById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var definitionId string
		var revisionId string
		var appId int32

		resp, httpRes, err := apiClient.RevisionsApi.GetAutomationV4ActionsAppIdDefinitionIdRevisionsRevisionIdGetById(context.Background(), definitionId, revisionId, appId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
