/*
Custom Workflow Actions

Testing FunctionsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package actions

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/automation/actions"
)

func Test_actions_FunctionsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FunctionsApiService DeleteAutomationV4ActionsAppIdDefinitionIdFunctionsFunctionTypeArchiveByFunctionType", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var definitionId string
		var functionType string
		var appId int32

		httpRes, err := apiClient.FunctionsApi.DeleteAutomationV4ActionsAppIdDefinitionIdFunctionsFunctionTypeArchiveByFunctionType(context.Background(), definitionId, functionType, appId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsApiService DeleteAutomationV4ActionsAppIdDefinitionIdFunctionsFunctionTypeFunctionIdArchive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var definitionId string
		var functionType string
		var functionId string
		var appId int32

		httpRes, err := apiClient.FunctionsApi.DeleteAutomationV4ActionsAppIdDefinitionIdFunctionsFunctionTypeFunctionIdArchive(context.Background(), definitionId, functionType, functionId, appId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsApiService GetAutomationV4ActionsAppIdDefinitionIdFunctionsFunctionTypeFunctionIdGetById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var definitionId string
		var functionType string
		var functionId string
		var appId int32

		resp, httpRes, err := apiClient.FunctionsApi.GetAutomationV4ActionsAppIdDefinitionIdFunctionsFunctionTypeFunctionIdGetById(context.Background(), definitionId, functionType, functionId, appId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsApiService GetAutomationV4ActionsAppIdDefinitionIdFunctionsFunctionTypeGetByFunctionType", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var definitionId string
		var functionType string
		var appId int32

		resp, httpRes, err := apiClient.FunctionsApi.GetAutomationV4ActionsAppIdDefinitionIdFunctionsFunctionTypeGetByFunctionType(context.Background(), definitionId, functionType, appId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsApiService GetAutomationV4ActionsAppIdDefinitionIdFunctionsGetPage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var definitionId string
		var appId int32

		resp, httpRes, err := apiClient.FunctionsApi.GetAutomationV4ActionsAppIdDefinitionIdFunctionsGetPage(context.Background(), definitionId, appId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsApiService PutAutomationV4ActionsAppIdDefinitionIdFunctionsFunctionTypeCreateOrReplaceByFunctionType", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var definitionId string
		var functionType string
		var appId int32

		resp, httpRes, err := apiClient.FunctionsApi.PutAutomationV4ActionsAppIdDefinitionIdFunctionsFunctionTypeCreateOrReplaceByFunctionType(context.Background(), definitionId, functionType, appId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FunctionsApiService PutAutomationV4ActionsAppIdDefinitionIdFunctionsFunctionTypeFunctionIdCreateOrReplace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var definitionId string
		var functionType string
		var functionId string
		var appId int32

		resp, httpRes, err := apiClient.FunctionsApi.PutAutomationV4ActionsAppIdDefinitionIdFunctionsFunctionTypeFunctionIdCreateOrReplace(context.Background(), definitionId, functionType, functionId, appId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
