/*
Companies

Testing BasicApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package companies

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/companies"
)

func Test_companies_BasicApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BasicApiService DeleteCrmV3ObjectsCompaniesCompanyIdArchive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string

		httpRes, err := apiClient.BasicApi.DeleteCrmV3ObjectsCompaniesCompanyIdArchive(context.Background(), companyId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService GetCrmV3ObjectsCompaniesCompanyIdGetById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string

		resp, httpRes, err := apiClient.BasicApi.GetCrmV3ObjectsCompaniesCompanyIdGetById(context.Background(), companyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService GetCrmV3ObjectsCompaniesGetPage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BasicApi.GetCrmV3ObjectsCompaniesGetPage(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService PatchCrmV3ObjectsCompaniesCompanyIdUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string

		resp, httpRes, err := apiClient.BasicApi.PatchCrmV3ObjectsCompaniesCompanyIdUpdate(context.Background(), companyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService PostCrmV3ObjectsCompaniesCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BasicApi.PostCrmV3ObjectsCompaniesCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
