/*
Products

Testing BasicApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package products

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/products"
)

func Test_products_BasicApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BasicApiService DeleteCrmV3ObjectsProductsProductIdArchive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var productId string

		httpRes, err := apiClient.BasicApi.DeleteCrmV3ObjectsProductsProductIdArchive(context.Background(), productId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService GetCrmV3ObjectsProductsGetPage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BasicApi.GetCrmV3ObjectsProductsGetPage(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService GetCrmV3ObjectsProductsProductIdGetById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var productId string

		resp, httpRes, err := apiClient.BasicApi.GetCrmV3ObjectsProductsProductIdGetById(context.Background(), productId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService PatchCrmV3ObjectsProductsProductIdUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var productId string

		resp, httpRes, err := apiClient.BasicApi.PatchCrmV3ObjectsProductsProductIdUpdate(context.Background(), productId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService PostCrmV3ObjectsProductsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BasicApi.PostCrmV3ObjectsProductsCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
