/*
Accounting Extension

Testing UserAccountsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package accounting

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/accounting"
)

func Test_accounting_UserAccountsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UserAccountsApiService DeleteCrmV3ExtensionsAccountingUserAccountsAccountIdArchive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var accountId string

		httpRes, err := apiClient.UserAccountsApi.DeleteCrmV3ExtensionsAccountingUserAccountsAccountIdArchive(context.Background(), accountId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UserAccountsApiService PutCrmV3ExtensionsAccountingUserAccountsReplace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.UserAccountsApi.PutCrmV3ExtensionsAccountingUserAccountsReplace(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
