/*
Accounting Extension

Testing SettingsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package accounting

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/accounting"
)

func Test_accounting_SettingsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SettingsApiService GetCrmV3ExtensionsAccountingSettingsAppIdGetById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var appId int32

		resp, httpRes, err := apiClient.SettingsApi.GetCrmV3ExtensionsAccountingSettingsAppIdGetById(context.Background(), appId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SettingsApiService PutCrmV3ExtensionsAccountingSettingsAppIdReplace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var appId int32

		httpRes, err := apiClient.SettingsApi.PutCrmV3ExtensionsAccountingSettingsAppIdReplace(context.Background(), appId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
