/*
Associations

Testing BatchApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package associations

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/associations"
)

func Test_associations_BatchApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BatchApiService PostCrmV3AssociationsFromObjectTypeToObjectTypeBatchArchiveArchive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fromObjectType string
		var toObjectType string

		httpRes, err := apiClient.BatchApi.PostCrmV3AssociationsFromObjectTypeToObjectTypeBatchArchiveArchive(context.Background(), fromObjectType, toObjectType).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BatchApiService PostCrmV3AssociationsFromObjectTypeToObjectTypeBatchCreateCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fromObjectType string
		var toObjectType string

		resp, httpRes, err := apiClient.BatchApi.PostCrmV3AssociationsFromObjectTypeToObjectTypeBatchCreateCreate(context.Background(), fromObjectType, toObjectType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BatchApiService PostCrmV3AssociationsFromObjectTypeToObjectTypeBatchReadRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fromObjectType string
		var toObjectType string

		resp, httpRes, err := apiClient.BatchApi.PostCrmV3AssociationsFromObjectTypeToObjectTypeBatchReadRead(context.Background(), fromObjectType, toObjectType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
