/*
CMS Site Search

Testing PublicApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package site-search

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/cms/site-search"
)

func Test_site-search_PublicApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PublicApiService GetCmsV3SiteSearchIndexedDataContentIdGetById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var contentId string

		resp, httpRes, err := apiClient.PublicApi.GetCmsV3SiteSearchIndexedDataContentIdGetById(context.Background(), contentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PublicApiService GetCmsV3SiteSearchSearchSearch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PublicApi.GetCmsV3SiteSearchSearchSearch(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
