/*
Deals

Testing BasicApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package deals

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/deals"
)

func Test_deals_BasicApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BasicApiService DeleteCrmV3ObjectsDealsDealIdArchive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dealId string

		httpRes, err := apiClient.BasicApi.DeleteCrmV3ObjectsDealsDealIdArchive(context.Background(), dealId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService GetCrmV3ObjectsDealsDealIdGetById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dealId string

		resp, httpRes, err := apiClient.BasicApi.GetCrmV3ObjectsDealsDealIdGetById(context.Background(), dealId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService GetCrmV3ObjectsDealsGetPage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BasicApi.GetCrmV3ObjectsDealsGetPage(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService PatchCrmV3ObjectsDealsDealIdUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dealId string

		resp, httpRes, err := apiClient.BasicApi.PatchCrmV3ObjectsDealsDealIdUpdate(context.Background(), dealId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService PostCrmV3ObjectsDealsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BasicApi.PostCrmV3ObjectsDealsCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
