/*
Subscriptions

Testing DefinitionApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package communications_status

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/communication-preferences/communications_status"
)

func Test_communications_status_DefinitionApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefinitionApiService GetCommunicationPreferencesV3DefinitionsGetPage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefinitionApi.GetCommunicationPreferencesV3DefinitionsGetPage(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
