/*
Marketing Events Extension

Testing SearchApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package marketing-events-beta

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/marketing/marketing-events-beta"
)

func Test_marketing-events-beta_SearchApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SearchApiService GetMarketingV3MarketingEventsEventsSearchDoSearch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SearchApi.GetMarketingV3MarketingEventsEventsSearchDoSearch(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
