/*
Feedback Submissions

Testing BasicApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package feedback_submissions

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/feedback_submissions"
)

func Test_feedback_submissions_BasicApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BasicApiService DeleteCrmV3ObjectsFeedbackSubmissionsFeedbackSubmissionIdArchive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var feedbackSubmissionId string

		httpRes, err := apiClient.BasicApi.DeleteCrmV3ObjectsFeedbackSubmissionsFeedbackSubmissionIdArchive(context.Background(), feedbackSubmissionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService GetCrmV3ObjectsFeedbackSubmissionsFeedbackSubmissionIdGetById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var feedbackSubmissionId string

		resp, httpRes, err := apiClient.BasicApi.GetCrmV3ObjectsFeedbackSubmissionsFeedbackSubmissionIdGetById(context.Background(), feedbackSubmissionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService GetCrmV3ObjectsFeedbackSubmissionsGetPage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BasicApi.GetCrmV3ObjectsFeedbackSubmissionsGetPage(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService PatchCrmV3ObjectsFeedbackSubmissionsFeedbackSubmissionIdUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var feedbackSubmissionId string

		resp, httpRes, err := apiClient.BasicApi.PatchCrmV3ObjectsFeedbackSubmissionsFeedbackSubmissionIdUpdate(context.Background(), feedbackSubmissionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BasicApiService PostCrmV3ObjectsFeedbackSubmissionsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BasicApi.PostCrmV3ObjectsFeedbackSubmissionsCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
