/*
Business Unit

Retrieve Business Unit information.

API version: v3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package business_units

import (
	"encoding/json"
)

// checks if the PublicBusinessUnitLogoMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicBusinessUnitLogoMetadata{}

// PublicBusinessUnitLogoMetadata A Business Unit's logo metadata
type PublicBusinessUnitLogoMetadata struct {
	// The logo's url
	LogoUrl *string `json:"logoUrl,omitempty"`
	// The logo's alt text
	LogoAltText *string `json:"logoAltText,omitempty"`
	// The logo's resized url
	ResizedUrl *string `json:"resizedUrl,omitempty"`
}

// NewPublicBusinessUnitLogoMetadata instantiates a new PublicBusinessUnitLogoMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicBusinessUnitLogoMetadata() *PublicBusinessUnitLogoMetadata {
	this := PublicBusinessUnitLogoMetadata{}
	return &this
}

// NewPublicBusinessUnitLogoMetadataWithDefaults instantiates a new PublicBusinessUnitLogoMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicBusinessUnitLogoMetadataWithDefaults() *PublicBusinessUnitLogoMetadata {
	this := PublicBusinessUnitLogoMetadata{}
	return &this
}

// GetLogoUrl returns the LogoUrl field value if set, zero value otherwise.
func (o *PublicBusinessUnitLogoMetadata) GetLogoUrl() string {
	if o == nil || IsNil(o.LogoUrl) {
		var ret string
		return ret
	}
	return *o.LogoUrl
}

// GetLogoUrlOk returns a tuple with the LogoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicBusinessUnitLogoMetadata) GetLogoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.LogoUrl) {
		return nil, false
	}
	return o.LogoUrl, true
}

// HasLogoUrl returns a boolean if a field has been set.
func (o *PublicBusinessUnitLogoMetadata) HasLogoUrl() bool {
	if o != nil && !IsNil(o.LogoUrl) {
		return true
	}

	return false
}

// SetLogoUrl gets a reference to the given string and assigns it to the LogoUrl field.
func (o *PublicBusinessUnitLogoMetadata) SetLogoUrl(v string) {
	o.LogoUrl = &v
}

// GetLogoAltText returns the LogoAltText field value if set, zero value otherwise.
func (o *PublicBusinessUnitLogoMetadata) GetLogoAltText() string {
	if o == nil || IsNil(o.LogoAltText) {
		var ret string
		return ret
	}
	return *o.LogoAltText
}

// GetLogoAltTextOk returns a tuple with the LogoAltText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicBusinessUnitLogoMetadata) GetLogoAltTextOk() (*string, bool) {
	if o == nil || IsNil(o.LogoAltText) {
		return nil, false
	}
	return o.LogoAltText, true
}

// HasLogoAltText returns a boolean if a field has been set.
func (o *PublicBusinessUnitLogoMetadata) HasLogoAltText() bool {
	if o != nil && !IsNil(o.LogoAltText) {
		return true
	}

	return false
}

// SetLogoAltText gets a reference to the given string and assigns it to the LogoAltText field.
func (o *PublicBusinessUnitLogoMetadata) SetLogoAltText(v string) {
	o.LogoAltText = &v
}

// GetResizedUrl returns the ResizedUrl field value if set, zero value otherwise.
func (o *PublicBusinessUnitLogoMetadata) GetResizedUrl() string {
	if o == nil || IsNil(o.ResizedUrl) {
		var ret string
		return ret
	}
	return *o.ResizedUrl
}

// GetResizedUrlOk returns a tuple with the ResizedUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicBusinessUnitLogoMetadata) GetResizedUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ResizedUrl) {
		return nil, false
	}
	return o.ResizedUrl, true
}

// HasResizedUrl returns a boolean if a field has been set.
func (o *PublicBusinessUnitLogoMetadata) HasResizedUrl() bool {
	if o != nil && !IsNil(o.ResizedUrl) {
		return true
	}

	return false
}

// SetResizedUrl gets a reference to the given string and assigns it to the ResizedUrl field.
func (o *PublicBusinessUnitLogoMetadata) SetResizedUrl(v string) {
	o.ResizedUrl = &v
}

func (o PublicBusinessUnitLogoMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicBusinessUnitLogoMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LogoUrl) {
		toSerialize["logoUrl"] = o.LogoUrl
	}
	if !IsNil(o.LogoAltText) {
		toSerialize["logoAltText"] = o.LogoAltText
	}
	if !IsNil(o.ResizedUrl) {
		toSerialize["resizedUrl"] = o.ResizedUrl
	}
	return toSerialize, nil
}

type NullablePublicBusinessUnitLogoMetadata struct {
	value *PublicBusinessUnitLogoMetadata
	isSet bool
}

func (v NullablePublicBusinessUnitLogoMetadata) Get() *PublicBusinessUnitLogoMetadata {
	return v.value
}

func (v *NullablePublicBusinessUnitLogoMetadata) Set(val *PublicBusinessUnitLogoMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicBusinessUnitLogoMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicBusinessUnitLogoMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicBusinessUnitLogoMetadata(val *PublicBusinessUnitLogoMetadata) *NullablePublicBusinessUnitLogoMetadata {
	return &NullablePublicBusinessUnitLogoMetadata{value: val, isSet: true}
}

func (v NullablePublicBusinessUnitLogoMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicBusinessUnitLogoMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
