/*
CrmPublicAssociationsServiceV4

Testing DefinitionsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package crm_associations

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/crm/crm_associations"
)

func Test_crm_associations_DefinitionsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefinitionsApiService DeleteCrmV4AssociationsFromObjectTypeToObjectTypeLabelsAssociationTypeIdArchive", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fromObjectType string
		var toObjectType string
		var associationTypeId int32

		httpRes, err := apiClient.DefinitionsApi.DeleteCrmV4AssociationsFromObjectTypeToObjectTypeLabelsAssociationTypeIdArchive(context.Background(), fromObjectType, toObjectType, associationTypeId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefinitionsApiService GetCrmV4AssociationsFromObjectTypeToObjectTypeLabelsGetAll", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fromObjectType string
		var toObjectType string

		resp, httpRes, err := apiClient.DefinitionsApi.GetCrmV4AssociationsFromObjectTypeToObjectTypeLabelsGetAll(context.Background(), fromObjectType, toObjectType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefinitionsApiService PostCrmV4AssociationsFromObjectTypeToObjectTypeLabelsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fromObjectType string
		var toObjectType string

		resp, httpRes, err := apiClient.DefinitionsApi.PostCrmV4AssociationsFromObjectTypeToObjectTypeLabelsCreate(context.Background(), fromObjectType, toObjectType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefinitionsApiService PutCrmV4AssociationsFromObjectTypeToObjectTypeLabelsUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fromObjectType string
		var toObjectType string

		httpRes, err := apiClient.DefinitionsApi.PutCrmV4AssociationsFromObjectTypeToObjectTypeLabelsUpdate(context.Background(), fromObjectType, toObjectType).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
