/*
Subscriptions

Testing StatusApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package communications-status

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/pyscht/hubspot-go-api/apis/communication-preferences/communications-status"
)

func Test_communications-status_StatusApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StatusApiService GetCommunicationPreferencesV3StatusEmailEmailAddressGetEmailStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var emailAddress string

		resp, httpRes, err := apiClient.StatusApi.GetCommunicationPreferencesV3StatusEmailEmailAddressGetEmailStatus(context.Background(), emailAddress).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StatusApiService PostCommunicationPreferencesV3SubscribeSubscribe", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.StatusApi.PostCommunicationPreferencesV3SubscribeSubscribe(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StatusApiService PostCommunicationPreferencesV3UnsubscribeUnsubscribe", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.StatusApi.PostCommunicationPreferencesV3UnsubscribeUnsubscribe(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
